version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  websocket-server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - websocket-server

volumes:
  redis-data:
